name: Go

# Определение событий, на которые реагирует workflow
on:
  push:
    branches:
      - first-iteration    # Запускает workflow при пуше в ветку first-iteration
    tags:
      - 'v*.*.*'  # Запускает workflow при добавлении тегов, например, v1.0.0

jobs:
  # Job для тестирования кода
  test:
    runs-on: ubuntu-latest
    container: golang:1.22

    steps:
      - uses: actions/checkout@v4

      - name: Run Unit Tests
        run: GOOS=linux GOARCH=amd64 go test

      - name: Run Linter
        run: |
          go vet ./...

      - name: Run Tests
        run: |
          go test -v ./...

  # Job для сборки и публикации Docker-образа
  deploy:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test  # Выполняется после успешного завершения тестов
    if: startsWith(github.ref, 'refs/tags/')  # Запускается только при наличии тега

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: avp8853/go_final_project_avp

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}